### ISSUE TITLE
Install issue with OctoPrint 1.3.6

### ISSUE THREAD

**Issue by dnewman-polar3d** [markwal/OctoPrint-PolarCloud#31]
Brand new 0.14 Octopi image.  Updated to 1.3.6 release.

Then install the Polar Cloud plugin.  Install runs fine and goes to completion with no errors.  Success is declared.  However, OctoPrint then says "Plugin Installed.  A plugin was installed successfully, however it was impossible to detect which one.  Please Restart OctoPrint to make sure everything will be registered properly." 

Clicking the "Restart now" button does a restart.  Once OctoPrint is back up, there is no sign whatsoever of the plugin being installed and thus it is not possible to enable it.

Repeat.... The install of the plugin goes really fast the second time as the libraries are already installed.  The isntall declares success again.  However, same message from OctoPrint about needing to restart.  After the restart, no sign of the plugin.

**Comment by dnewman-polar3d** [comment]
2017-12-13 00:54:55,161 - octoprint.plugins.pluginmanager - INFO - Installing plugin from https://github.com/markwal/OctoPrint-PolarCloud/archive/master.zip
    2017-12-13 00:57:50,583 - py.warnings - WARNING - /home/pi/oprint/local/lib/python2.7/site-packages/OctoPrint-1.3.6-py2.7.egg/octoprint/plugin/core.py:1538: UserWarning: No PKG-INFO found for package: octoprint_polarcloud
      warnings.warn('No PKG-INFO found for package: %s' % self.package_name)
    
    2017-12-13 00:57:50,614 - octoprint.plugin.core - ERROR - Error loading plugin polarcloud
    Traceback (most recent call last):
      File "/home/pi/oprint/local/lib/python2.7/site-packages/OctoPrint-1.3.6-py2.7.egg/octoprint/plugin/core.py", line 732, in _import_plugin
        instance = imp.load_module(key, f, filename, description)
      File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_polarcloud/__init__.py", line 43, in <module>
        from OpenSSL import crypto
      File "/home/pi/oprint/local/lib/python2.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
        from OpenSSL import crypto, SSL
      File "/home/pi/oprint/local/lib/python2.7/site-packages/OpenSSL/crypto.py", line 12, in <module>
        from cryptography import x509
      File "/home/pi/oprint/local/lib/python2.7/site-packages/cryptography/x509/__init__.py", line 7, in <module>
        from cryptography.x509 import certificate_transparency
      File "/home/pi/oprint/local/lib/python2.7/site-packages/cryptography/x509/certificate_transparency.py", line 8, in <module>
        from enum import Enum
    ImportError: No module named enum
    2017-12-13 00:57:50,629 - octoprint.plugins.pluginmanager - WARNING - The plugin was installed successfully, but couldn't be found afterwards to initialize properly during runtime. Please restart OctoPrint.
    2017-12-13 00:58:04,239 - octoprint.server.api.system - INFO - Performing command for core:restart: sudo service octoprint restart
    2017-12-13 00:58:04,384 - octoprint.server - INFO - Shutting down...
    2017-12-13 00:58:05,281 - octoprint.events - INFO - Processing shutdown event, this will be our last event
    2017-12-13 00:58:05,293 - octoprint.events - INFO - Event loop shut down
    2017-12-13 00:58:05,305 - octoprint.server - INFO - Goodbye!
    2017-12-13 00:58:10,198 - octoprint.startup - INFO - ******************************************************************************
    2017-12-13 00:58:10,199 - octoprint.startup - INFO - Starting OctoPrint 1.3.6
    2017-12-13 00:58:10,200 - octoprint.startup - INFO - ******************************************************************************
    2017-12-13 00:58:11,909 - octoprint.startup - INFO - Blacklist processing done

**Comment by dnewman-polar3d** [comment]
FYI, no difference if I do

    source ~/oprint/bin/activate
    pip install -U setuptools

and then try to install again.  Same error.

**Comment by dnewman-polar3d** [comment]
Was fixed by Commit 1af41c2.
