### ISSUE TITLE
Polar cloud plugin installation error

### ISSUE THREAD

**Issue by drkbalamurugan** [markwal/OctoPrint-PolarCloud#46]
Installing plugin from uploaded archive...
c:\octoprint\venv\scripts\python.exe -m pip install c:/users/user/appdata/local/temp/tmp2bpg6e.zip --no-cache-dir
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Processing c:\users\user\appdata\local\temp\tmp2bpg6e.zip
Requirement already satisfied: OctoPrint in c:\octoprint\venv\lib\site-packages (from OctoPrint-PolarCloud==1.3) (1.3.10)
Collecting SocketIO-client (from OctoPrint-PolarCloud==1.3)
Downloading https://files.pythonhosted.org/packages/12/d4/abeb2596c2f16276c66910362b27d04b8d2cf12a746dcccf1d00de3f691b/socketIO-client-0.7.2.tar.gz
Collecting pyopenssl (from OctoPrint-PolarCloud==1.3)
Downloading https://files.pythonhosted.org/packages/01/c8/ceb170d81bd3941cbeb9940fc6cc2ef2ca4288d0ca8929ea4db5905d904d/pyOpenSSL-19.0.0-py2.py3-none-any.whl (53kB)
Collecting Pillow (from OctoPrint-PolarCloud==1.3)
Downloading https://files.pythonhosted.org/packages/a5/66/433aa868409dcacdd431e2b73ea0b21d66f0ed3911a3c25305eec1d27900/Pillow-5.4.1-cp27-cp27m-win32.whl (1.6MB)
Requirement already satisfied: Flask-Principal<0.4,>=0.3.5 in c:\octoprint\venv\lib\site-packages (from OctoPrint->OctoPrint-PolarCloud==1.3) (0.3.5)
Requirement already satisfied: markdown<2.7,>=2.6.9 in c:\octoprint\venv\lib\site-packages (from OctoPrint->OctoPrint-PolarCloud==1.3) (2.6.11)
Requirement already satisfied: pylru<1.1,>=1.0.9 in c:\octoprint\venv\lib\site-packages (from OctoPrint->OctoPrint-PolarCloud==1.3) (1.0.9)
Requirement already satisfied: frozendict<1.3,>=1.2 in c:\octoprint\venv\lib\site-packages (from OctoPrint->OctoPrint-PolarCloud==1.3) (1.2)
Requirement already satisfied: future<0.16,>=0.15.2 in c:\octoprint\venv\lib\site-packages (from OctoPrint->OctoPrint-PolarCloud==1.3) (0.15.2)
Requirement already satisfied: flask<0.11,>=0.10.1 in c:\octoprint\venv\lib\site-packages (from OctoPrint->OctoPrint-PolarCloud==1.3) (0.10.1)
Requirement already satisfied: feedparser<5.3,>=5.2.1 in c:\octoprint\venv\lib\site-packages (from OctoPrint->OctoPrint-PolarCloud==1.3) (5.2.1)
Requirement already satisfied: awesome-slugify<1.7,>=1.6.5 in c:\octoprint\venv\lib\site-packages (from OctoPrint->OctoPrint-PolarCloud==1.3) (1.6.5)
Requirement already satisfied: watchdog<0.9,>=0.8.3 in c:\octoprint\venv\lib\site-packages (from OctoPrint->OctoPrint-PolarCloud==1.3) (0.8.3)
Requirement already satisfied: Flask-Assets<0.11,>=0.10 in c:\octoprint\venv\lib\site-packages (from OctoPrint->OctoPrint-PolarCloud==1.3) (0.10)
Requirement already satisfied: requests<3,>=2.18.4 in c:\octoprint\venv\lib\site-packages (from OctoPrint->OctoPrint-PolarCloud==1.3) (2.21.0)
Requirement already satisfied: websocket-client<0.41,>=0.40.0 in c:\octoprint\venv\lib\site-packages (from OctoPrint->OctoPrint-PolarCloud==1.3) (0.40.0)
Requirement already satisfied: Click<6.3,>=6.2 in c:\octoprint\venv\lib\site-packages (from OctoPrint->OctoPrint-PolarCloud==1.3) (6.2)
Requirement already satisfied: Flask-Babel<0.10,>=0.9 in c:\octoprint\venv\lib\site-packages (from OctoPrint->OctoPrint-PolarCloud==1.3) (0.9)
Requirement already satisfied: psutil<5.5,>=5.4.6 in c:\octoprint\venv\lib\site-packages (from OctoPrint->OctoPrint-PolarCloud==1.3) (5.4.8)
Requirement already satisfied: Jinja2<2.9,>=2.8.1 in c:\octoprint\venv\lib\site-packages (from OctoPrint->OctoPrint-PolarCloud==1.3) (2.8.1)
Requirement already satisfied: emoji<0.5,>=0.4.5 in c:\octoprint\venv\lib\site-packages (from OctoPrint->OctoPrint-PolarCloud==1.3) (0.4.5)
Requirement already satisfied: pyserial<3.5,>=3.4 in c:\octoprint\venv\lib\site-packages (from OctoPrint->OctoPrint-PolarCloud==1.3) (3.4)
Requirement already satisfied: regex!=2018.11.6 in c:\octoprint\venv\lib\site-packages (from OctoPrint->OctoPrint-PolarCloud==1.3) (2019.1.23)
Requirement already satisfied: Flask-Login<0.3,>=0.2.11 in c:\octoprint\venv\lib\site-packages (from OctoPrint->OctoPrint-PolarCloud==1.3) (0.2.11)
Requirement already satisfied: semantic-version<2.5,>=2.4.2 in c:\octoprint\venv\lib\site-packages (from OctoPrint->OctoPrint-PolarCloud==1.3) (2.4.2)
Requirement already satisfied: wrapt<1.11,>=1.10.11 in c:\octoprint\venv\lib\site-packages (from OctoPrint->OctoPrint-PolarCloud==1.3) (1.10.11)
Requirement already satisfied: monotonic<1.4,>=1.3 in c:\octoprint\venv\lib\site-packages (from OctoPrint->OctoPrint-PolarCloud==1.3) (1.3)
Requirement already satisfied: PyYAML<3.11,>=3.10 in c:\octoprint\venv\lib\site-packages (from OctoPrint->OctoPrint-PolarCloud==1.3) (3.10)
Requirement already satisfied: pkginfo<1.5,>=1.4.2 in c:\octoprint\venv\lib\site-packages (from OctoPrint->OctoPrint-PolarCloud==1.3) (1.4.2)
Requirement already satisfied: netifaces<0.11,>=0.10.6 in c:\octoprint\venv\lib\site-packages (from OctoPrint->OctoPrint-PolarCloud==1.3) (0.10.9)
Requirement already satisfied: chainmap<1.1,>=1.0.2 in c:\octoprint\venv\lib\site-packages (from OctoPrint->OctoPrint-PolarCloud==1.3) (1.0.2)
Requirement already satisfied: python-dateutil<2.7,>=2.6.1 in c:\octoprint\venv\lib\site-packages (from OctoPrint->OctoPrint-PolarCloud==1.3) (2.6.1)
Requirement already satisfied: netaddr<0.8,>=0.7.19 in c:\octoprint\venv\lib\site-packages (from OctoPrint->OctoPrint-PolarCloud==1.3) (0.7.19)
Requirement already satisfied: futures<3.2,>=3.1.1 in c:\octoprint\venv\lib\site-packages (from OctoPrint->OctoPrint-PolarCloud==1.3) (3.1.1)
Requirement already satisfied: rsa<3.3,>=3.2.3 in c:\octoprint\venv\lib\site-packages (from OctoPrint->OctoPrint-PolarCloud==1.3) (3.2.3)
Requirement already satisfied: sarge==0.1.5post0 in c:\octoprint\venv\lib\site-packages (from OctoPrint->OctoPrint-PolarCloud==1.3) (0.1.5.post0)
Requirement already satisfied: werkzeug<0.9,>=0.8.3 in c:\octoprint\venv\lib\site-packages (from OctoPrint->OctoPrint-PolarCloud==1.3) (0.8.3)
Requirement already satisfied: tornado==4.5.3 in c:\octoprint\venv\lib\site-packages (from OctoPrint->OctoPrint-PolarCloud==1.3) (4.5.3)
Requirement already satisfied: scandir<1.4,>=1.3 in c:\octoprint\venv\lib\site-packages (from OctoPrint->OctoPrint-PolarCloud==1.3) (1.3)
Requirement already satisfied: six in c:\octoprint\venv\lib\site-packages (from SocketIO-client->OctoPrint-PolarCloud==1.3) (1.12.0)
Collecting cryptography>=2.3 (from pyopenssl->OctoPrint-PolarCloud==1.3)
Downloading https://files.pythonhosted.org/packages/00/3b/3973245e762361378cff5d596d734a8c74b4fcb400dbcb5403e11b31035c/cryptography-2.5-cp27-cp27m-win32.whl (1.3MB)
Requirement already satisfied: blinker in c:\octoprint\venv\lib\site-packages (from Flask-Principal<0.4,>=0.3.5->OctoPrint->OctoPrint-PolarCloud==1.3) (1.4)
Requirement already satisfied: itsdangerous>=0.21 in c:\octoprint\venv\lib\site-packages (from flask<0.11,>=0.10.1->OctoPrint->OctoPrint-PolarCloud==1.3) (1.1.0)
Requirement already satisfied: Unidecode<0.05,>=0.04.14 in c:\octoprint\venv\lib\site-packages (from awesome-slugify<1.7,>=1.6.5->OctoPrint->OctoPrint-PolarCloud==1.3) (0.4.21)
Requirement already satisfied: pathtools>=0.1.1 in c:\octoprint\venv\lib\site-packages (from watchdog<0.9,>=0.8.3->OctoPrint->OctoPrint-PolarCloud==1.3) (0.1.2)
Requirement already satisfied: argh>=0.24.1 in c:\octoprint\venv\lib\site-packages (from watchdog<0.9,>=0.8.3->OctoPrint->OctoPrint-PolarCloud==1.3) (0.26.2)
Requirement already satisfied: webassets>=0.10 in c:\octoprint\venv\lib\site-packages (from Flask-Assets<0.11,>=0.10->OctoPrint->OctoPrint-PolarCloud==1.3) (0.12.1)
Requirement already satisfied: certifi>=2017.4.17 in c:\octoprint\venv\lib\site-packages (from requests<3,>=2.18.4->OctoPrint->OctoPrint-PolarCloud==1.3) (2018.11.29)
Requirement already satisfied: idna<2.9,>=2.5 in c:\octoprint\venv\lib\site-packages (from requests<3,>=2.18.4->OctoPrint->OctoPrint-PolarCloud==1.3) (2.8)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\octoprint\venv\lib\site-packages (from requests<3,>=2.18.4->OctoPrint->OctoPrint-PolarCloud==1.3) (3.0.4)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in c:\octoprint\venv\lib\site-packages (from requests<3,>=2.18.4->OctoPrint->OctoPrint-PolarCloud==1.3) (1.24.1)
Requirement already satisfied: speaklater>=1.2 in c:\octoprint\venv\lib\site-packages (from Flask-Babel<0.10,>=0.9->OctoPrint->OctoPrint-PolarCloud==1.3) (1.3)
Requirement already satisfied: Babel>=1.0 in c:\octoprint\venv\lib\site-packages (from Flask-Babel<0.10,>=0.9->OctoPrint->OctoPrint-PolarCloud==1.3) (2.6.0)
Requirement already satisfied: MarkupSafe in c:\octoprint\venv\lib\site-packages (from Jinja2<2.9,>=2.8.1->OctoPrint->OctoPrint-PolarCloud==1.3) (1.1.0)
Requirement already satisfied: pyasn1>=0.1.3 in c:\octoprint\venv\lib\site-packages (from rsa<3.3,>=3.2.3->OctoPrint->OctoPrint-PolarCloud==1.3) (0.4.5)
Requirement already satisfied: backports-abc>=0.4 in c:\octoprint\venv\lib\site-packages (from tornado==4.5.3->OctoPrint->OctoPrint-PolarCloud==1.3) (0.5)
Requirement already satisfied: singledispatch in c:\octoprint\venv\lib\site-packages (from tornado==4.5.3->OctoPrint->OctoPrint-PolarCloud==1.3) (3.4.0.3)
Collecting enum34; python_version < "3" (from cryptography>=2.3->pyopenssl->OctoPrint-PolarCloud==1.3)
Downloading https://files.pythonhosted.org/packages/c5/db/e56e6b4bbac7c4a06de1c50de6fe1ef3810018ae11732a50f15f62c7d050/enum34-1.1.6-py2-none-any.whl
Collecting cffi!=1.11.3,>=1.8 (from cryptography>=2.3->pyopenssl->OctoPrint-PolarCloud==1.3)
Downloading https://files.pythonhosted.org/packages/3a/84/9d1bf29b212853087318696c38241a3af65b33ea2edaabad11f26826ecf4/cffi-1.11.5-cp27-cp27m-win32.whl (153kB)
Collecting asn1crypto>=0.21.0 (from cryptography>=2.3->pyopenssl->OctoPrint-PolarCloud==1.3)
Downloading https://files.pythonhosted.org/packages/ea/cd/35485615f45f30a510576f1a56d1e0a7ad7bd8ab5ed7cdc600ef7cd06222/asn1crypto-0.24.0-py2.py3-none-any.whl (101kB)
Collecting ipaddress; python_version < "3" (from cryptography>=2.3->pyopenssl->OctoPrint-PolarCloud==1.3)
Downloading https://files.pythonhosted.org/packages/fc/d0/7fc3a811e011d4b388be48a0e381db8d990042df54aa4ef4599a31d39853/ipaddress-1.0.22-py2.py3-none-any.whl
Requirement already satisfied: pytz>=0a in c:\octoprint\venv\lib\site-packages (from Babel>=1.0->Flask-Babel<0.10,>=0.9->OctoPrint->OctoPrint-PolarCloud==1.3) (2018.9)
Collecting pycparser (from cffi!=1.11.3,>=1.8->cryptography>=2.3->pyopenssl->OctoPrint-PolarCloud==1.3)
Downloading https://files.pythonhosted.org/packages/68/9e/49196946aee219aead1290e00d1e7fdeab8567783e83e1b9ab5585e6206a/pycparser-2.19.tar.gz (158kB)
Exception:
Traceback (most recent call last):
File "c:\octoprint\venv\lib\site-packages\pip\_internal\cli\base_command.py", line 176, in main
status = self.run(options, args)
File "c:\octoprint\venv\lib\site-packages\pip\_internal\commands\install.py", line 346, in run
session=session, autobuilding=True
File "c:\octoprint\venv\lib\site-packages\pip\_internal\wheel.py", line 848, in build
assert building_is_possible
AssertionError
You are using pip version 19.0, however version 19.0.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
Error!
Could not parse output from pip, see plugin_pluginmanager_console.log for generated output

**Comment by mfamilia** [comment]
Hey, you can bypass this by installing it manually through ssh

```
ssh pi@octopi.local
...
/home/pi/oprint/bin/python2 -m pip install https://github.com/markwal/OctoPrint-PolarCloud/archive/master.zip --no-cache-dir
```
