### ISSUE TITLE
Install problem with Babel?

### ISSUE THREAD

**Issue by kompressor2279** [markwal/OctoPrint-PolarCloud#52]
Trying to install PolarCloud and it keeps throwing an error.

I actually had it installed before and it was working but something happened during an update and it no longer was in the list of installed Plugins.

Raspberry Pi 3 Model B Plus Rev 1.3
octopi_version: 0.15.1
pip: 9.0.3
python: 2.7.13
OctoPrint 1.4.2

The octoprint.log gives some interesting output.
"2020-08-20 11:32:07,495 - octoprint.plugins.pluginmanager - INFO - Installing plugin from https://github.com/markwal/OctoPrint-PolarCloud/archive/master.zip
2020-08-20 11:32:09,083 - octoprint.plugin.core - ERROR - Error loading plugin polarcloud
Traceback (most recent call last):
File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint/plugin/core.py", line 972, in _import_plugin
module = _load_module(module_name, spec)
File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint/plugin/core.py", line 71, in _load_module
return imp.load_module(name, f, filename, details)
File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_polarcloud/init.py", line 47, in
from flask.ext.babel import gettext, _
ImportError: No module named ext.babel
2020-08-20 11:32:09,440 - octoprint.plugin.core - INFO - Plugin OctoPrint Anywhere (1.0.21) is disabled.
2020-08-20 11:32:17,646 - octoprint.plugins.pluginmanager - ERROR - Installing the plugin from https://github.com/markwal/OctoPrint-PolarCloud/archive/master.zip failed, could not parse output from pip. See plugin_pluginmanager_console.log for generated output
2020-08-20 11:32:17,652 - octoprint.util - WARNING - Could not delete temporary directory /tmp/tmpHONmaO: [Errno 21] Is a directory: '/tmp/tmpHONmaO'"

Someone on another forum said the plugin is using a long deprecated method of importing Babel - in OctoPrint 1.4.1 the dependency was updated and this was removed. All that needs to happen is the author to change flask.ext.babel to flask-babel.

Not sure if this helps.

**Comment by wjsteele** [comment]
Oh... that's extremely helpful.  I'll see if I can push the devs to make that change!

Thanks,

Bill

**Comment by wjsteele** [comment]
Ok... Mark just posted a fix for this.

**Comment by markwal** [comment]
Fixed in 1.10
